

import type { LucideIcon } from 'lucide-react';
import {
  Circle,
  Code2,
  Command,
  Container,
  FileText,
  Gem,
  GitBranch,
  Monitor,
  Shell,
  Terminal,
  Waves,
  Zap,
} from 'lucide-react';

export type ShellType =
  | 'powershell'
  | 'cmd'
  | 'bash'
  | 'node'
  | 'python'
  | 'gitbash'
  | 'wsl'
  | 'zsh'
  | 'fish'
  | 'ruby'
  | 'php'
  | 'docker';

export interface ShellConfig {
  name: string;
  prompt: string;
  color: string;
  icon: LucideIcon;
  commands: string[];
  extensions: string[];
}

export interface TerminalCommand {
  command: string;
  args: string[];
  timestamp: Date;
  output?: string;
  error?: string;
  exitCode?: number;
}

export interface TerminalHistory {
  commands: TerminalCommand[];
  currentIndex: number;
}

export interface TerminalTab {
  id: string;
  name: string;
  shell: ShellType;
  isActive: boolean;
  history: TerminalHistory;
  currentDirectory: string;
}


export const SHELL_CONFIGS: Record<ShellType, ShellConfig> = {
  powershell: {
    name: 'PowerShell',
    prompt: 'PS C:\\>',
    color: '#0078D4',
    icon: Terminal,
    commands: [
      'Get-ChildItem',
      'ls',
      'dir',
      'Set-Location',
      'cd',
      'New-Item',
      'ni',
      'Remove-Item',
      'rm',
      'del',
      'Get-Content',
      'cat',
      'type',
      'Clear-Host',
      'cls',
      'Copy-Item',
      'cp',
      'Move-Item',
      'mv',
      'Rename-Item',
      'ren',
      'Test-Path',
      'Get-Process',
      'ps',
      'Stop-Process',
      'kill',
      'Start-Process',
      'start',
      'Get-Service',
      'Start-Service',
      'Stop-Service',
      'Restart-Service',
      'Invoke-WebRequest',
      'wget',
      'curl',
      'ConvertTo-Json',
      'ConvertFrom-Json',
    ],
    extensions: ['.ps1', '.psm1', '.psd1'],
  },
  cmd: {
    name: 'Command Prompt',
    prompt: 'C:\\>',
  color: '#00A6D7',
    icon: Command,
    commands: [
      'dir',
      'cd',
      'mkdir',
      'md',
      'rmdir',
      'rd',
      'del',
      'erase',
      'copy',
      'xcopy',
      'move',
      'ren',
      'rename',
      'type',
      'cls',
      'echo',
      'set',
      'path',
      'tree',
      'tasklist',
      'taskkill',
      'ping',
      'ipconfig',
      'netstat',
      'systeminfo',
    ],
    extensions: ['.bat', '.cmd'],
  },
  bash: {
    name: 'Bash',
    prompt: '$ ',
    color: '#28A745',
    icon: Shell,
    commands: [
      'ls',
      'cd',
      'pwd',
      'mkdir',
      'rmdir',
      'rm',
      'cp',
      'mv',
      'cat',
      'less',
      'more',
      'head',
      'tail',
      'grep',
      'find',
      'which',
      'whereis',
      'clear',
      'history',
      'ps',
      'kill',
      'killall',
      'top',
      'htop',
      'df',
      'du',
      'free',
      'uname',
      'whoami',
      'id',
      'groups',
      'sudo',
      'chmod',
      'chown',
      'tar',
      'zip',
      'unzip',
    ],
    extensions: ['.sh', '.bash'],
  },
  node: {
    name: 'Node.js',
    prompt: '> ',
    color: '#6CC04A',
    icon: Circle,
    commands: [
      'console.log',
      'require',
      'module.exports',
      'process.exit',
      'process.argv',
      'process.env',
      'fs.readFile',
      'fs.writeFile',
      'path.join',
      'path.resolve',
    ],
    extensions: ['.js', '.mjs', '.cjs'],
  },
  python: {
    name: 'Python',
    prompt: '>>> ',
    color: '#3776AB',
    icon: FileText,
    commands: [
      'print',
      'input',
      'len',
      'type',
      'str',
      'int',
      'float',
      'list',
      'dict',
      'range',
      'enumerate',
      'zip',
      'map',
      'filter',
      'lambda',
      'def',
      'class',
      'import',
      'from',
      'as',
      'try',
      'except',
      'finally',
      'with',
      'open',
    ],
    extensions: ['.py', '.pyw', '.pyi'],
  },
  gitbash: {
    name: 'Git Bash',
    prompt: '$ ',
    color: '#F1502F',
    icon: GitBranch,
    commands: [
      'git',
      'ls',
      'cd',
      'pwd',
      'mkdir',
      'rmdir',
      'rm',
      'cp',
      'mv',
      'cat',
      'less',
      'more',
      'head',
      'tail',
      'grep',
      'find',
      'which',
      'whereis',
      'clear',
      'history',
      'ps',
      'kill',
      'killall',
      'top',
      'df',
      'du',
      'free',
      'uname',
      'whoami',
      'id',
      'groups',
      'sudo',
      'chmod',
      'chown',
      'tar',
      'zip',
      'unzip',
      'git init',
      'git clone',
      'git add',
      'git commit',
      'git push',
      'git pull',
      'git status',
      'git log',
      'git branch',
      'git checkout',
      'git merge',
    ],
    extensions: ['.sh', '.bash', '.git'],
  },
  wsl: {
    name: 'WSL Ubuntu',
    prompt: '$ ',
    color: '#E95420',
    icon: Monitor,
    commands: [
      'ls',
      'cd',
      'pwd',
      'mkdir',
      'rmdir',
      'rm',
      'cp',
      'mv',
      'cat',
      'less',
      'more',
      'head',
      'tail',
      'grep',
      'find',
      'which',
      'whereis',
      'clear',
      'history',
      'ps',
      'kill',
      'killall',
      'top',
      'htop',
      'df',
      'du',
      'free',
      'uname',
      'whoami',
      'id',
      'groups',
      'sudo',
      'chmod',
      'chown',
      'tar',
      'zip',
      'unzip',
      'apt',
      'apt-get',
      'snap',
      'systemctl',
      'service',
      'mount',
      'umount',
    ],
    extensions: ['.sh', '.bash', '.deb'],
  },
  zsh: {
    name: 'Zsh (Oh My Zsh)',
    prompt: '➜ ~ ',
    color: '#1DB954',
    icon: Zap,
    commands: [
      'ls',
      'cd',
      'pwd',
      'mkdir',
      'rmdir',
      'rm',
      'cp',
      'mv',
      'cat',
      'less',
      'more',
      'head',
      'tail',
      'grep',
      'find',
      'which',
      'whereis',
      'clear',
      'history',
      'ps',
      'kill',
      'killall',
      'top',
      'htop',
      'df',
      'du',
      'free',
      'uname',
      'whoami',
      'id',
      'groups',
      'sudo',
      'chmod',
      'chown',
      'tar',
      'zip',
      'unzip',
      'oh-my-zsh',
      'omz',
      'zsh',
      'source',
      'alias',
      'unalias',
      'autoload',
    ],
    extensions: ['.zsh', '.sh'],
  },
  fish: {
    name: 'Fish Shell',
    prompt: '~ ❯ ',
    color: '#00D492',
    icon: Waves,
    commands: [
      'ls',
      'cd',
      'pwd',
      'mkdir',
      'rmdir',
      'rm',
      'cp',
      'mv',
      'cat',
      'less',
      'more',
      'head',
      'tail',
      'grep',
      'find',
      'which',
      'whereis',
      'clear',
      'history',
      'ps',
      'kill',
      'killall',
      'top',
      'htop',
      'df',
      'du',
      'free',
      'uname',
      'whoami',
      'id',
      'groups',
      'sudo',
      'chmod',
      'chown',
      'tar',
      'zip',
      'unzip',
      'fish',
      'funced',
      'funcsave',
      'set',
      'abbr',
      'fish_config',
    ],
    extensions: ['.fish'],
  },
  ruby: {
    name: 'Ruby IRB',
    prompt: 'irb> ',
    color: '#CC342D',
    icon: Gem,
    commands: [
      'puts',
      'print',
      'p',
      'gets',
      'chomp',
      'length',
      'size',
      'class',
      'methods',
      'def',
      'end',
      'if',
      'elsif',
      'else',
      'unless',
      'case',
      'when',
      'while',
      'until',
      'for',
      'in',
      'do',
      'break',
      'next',
      'return',
      'yield',
      'block_given?',
      'require',
      'load',
      'gem',
      'bundle',
      'rake',
      'rails',
    ],
    extensions: ['.rb', '.rake', '.gemspec'],
  },
  php: {
    name: 'PHP Interactive',
    prompt: 'php> ',
    color: '#777BB4',
    icon: Code2,
    commands: [
      'echo',
      'print',
      'var_dump',
      'print_r',
      'die',
      'exit',
      'isset',
      'empty',
      'count',
      'strlen',
      'array',
      'function',
      'class',
      'interface',
      'trait',
      'namespace',
      'use',
      'include',
      'require',
      'include_once',
      'require_once',
      'composer',
      'php',
      'phpunit',
      'artisan',
    ],
    extensions: ['.php', '.phtml', '.inc'],
  },
  docker: {
    name: 'Docker',
    prompt: 'docker> ',
    color: '#2496ED',
    icon: Container,
    commands: [
      'docker',
      'docker run',
      'docker build',
      'docker pull',
      'docker push',
      'docker images',
      'docker ps',
      'docker stop',
      'docker start',
      'docker restart',
      'docker rm',
      'docker rmi',
      'docker exec',
      'docker logs',
      'docker inspect',
      'docker-compose',
      'docker-compose up',
      'docker-compose down',
      'docker-compose build',
      'docker-compose logs',
      'docker-compose ps',
      'docker-compose exec',
    ],
    extensions: ['Dockerfile', '.dockerignore', 'docker-compose.yml'],
  },
};


export const COMMON_COMMANDS = [
  'help',
  'exit',
  'quit',
  'clear',
  'history',
  'echo',
  'git',
  'npm',
  'yarn',
  'node',
  'python',
  'pip',
  'code',
  'notepad',
  'start',
  'explorer',
];


export const COMMAND_CATEGORIES = {
  file: ['ls', 'dir', 'cat', 'type', 'head', 'tail', 'find', 'locate'],
  directory: ['cd', 'mkdir', 'rmdir', 'pwd', 'tree'],
  process: ['ps', 'kill', 'top', 'tasklist', 'taskkill'],
  network: ['ping', 'curl', 'wget', 'netstat', 'ipconfig'],
  system: ['whoami', 'uname', 'systeminfo', 'date', 'time'],
  git: ['git status', 'git add', 'git commit', 'git push', 'git pull'],
  npm: ['npm install', 'npm start', 'npm run', 'npm test', 'npm build'],
};
